import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/ui/NavBar";

export const metadata: Metadata = {
  title: "Eccomerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar logo="LOGO" />
        <div className="pt-[50px] max-w-[1500px] m-auto ">{children}</div>
      </body>
    </html>
  );
}
